### ISSUE TITLE
Broken in "typescript": "4.2.4"

### ISSUE THREAD

**Issue by Jtfinlay** [Mobius5150/ts-api-decorators#20]
The `args` object is undefined when calling `return Reflect.getMetadata(this.ApiMethodParamsMetadataKey, target, key) || [];` for later version of TS.

This leads to failure later on when routing calls,

```
"TypeError: Cannot read property 'name' of undefined\n    at ManagedApi.<anonymous> (d:\\repos\\backend\\node_modules\\ts-api-decorators\\dist\\apiManagement\\ManagedApi.js:288:75)\n    at Generator.next (<anonymous>)\n    at d:\\repos\\backend\\node_modules\\ts-api-decorators\\dist\\apiManagement\\ManagedApi.js:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (d:\\repos\\backend\\node_modules\\ts-api-decorators\\dist\\apiManagement\\ManagedApi.js:4:12)\n    at ManagedApi.getHandlerArg (d:\\repos\\backend\\node_modules\\ts-api-decorators\\dist\\apiManagement\\ManagedApi.js:266:16)\n    at ManagedApi.<anonymous> (d:\\repos\\backend\\node_modules\\ts-api-decorators\\dist\\apiManagement\\ManagedApi.js:192:43)\n    at Generator.next (<anonymous>)\n    at d:\\repos\\backend\\node_modules\\ts-api-decorators\\dist\\apiManagement\\ManagedApi.js:8:71\n    at new Promise (<anonymous>)"
```

Trying to figure out what changed, but sounds like Reflect package is experimental, so liable to change in different versions.

**Comment by Mobius5150** [comment]
@Jtfinlay should be fixed by #24
